### ISSUE TITLE
Test transaction ordering

### ISSUE THREAD

**Issue by shenkeyao** [EspressoSystems/marketplace-builder-core#53]
Add tests to ensure we provide ordering for the Nitro builder requirement.

Relevant discussion starts from here: https://espresso.zulipchat.com/#narrow/stream/330967-Sequencer/topic/Builder.20API.20to.20support.20Nitro.20sequencer/near/456836223.

**Comment by dailinsubjam** [comment]
Pasted from Zulip:
Basically what should still result in correct txn order

- leader doesn't propose transactions we've given on one of the views
- leader proposes only first few of transactions we've given
- leader proposes transactions we didn't give out yet (simulating a case where it received those from elsewhere)
- leader doesn't propose at all
- leader proposes with a bad proposal on one of the views

What we should handle with tweaks to the test
- leader proposes transactions we've given out interspersed with other transactions
- chain forks, with one chain proposing transactions we've given and the other not (we should give out the next batch if responding for first chain and both batches for the other)

What we can't handle
- leader proposes transactions in modified order
- leader skips any transactions
